### ISSUE TITLE
title 根据当前浏览的api变更名称

### ISSUE THREAD

**Issue by Sczlog** [smartxworks/cloudtower-api-doc-tauri#81]
当前处于某个 api 下的时候， title 不会变化

![image](https://github.com/smartxworks/cloudtower-api-doc-tauri/assets/29588646/aea1f3a6-6eb3-4e46-9621-ace06a46de98)

如果可以显示对应的 api，分享链接时会更加直接

**Comment by netweng** [comment]
看了一下，目前 redoc 不开放可以监听到 menu item 改变了的 props， 做了其他尝试目前也没有其他接口可以监听到 url changed 了之类的。

这个优化目前 by design， 不处理了。
